version: 2

sphinx:
  configuration: docs/conf.py

formats:
  - epub
  - pdf

python:
   install:
      - method: pip
        path: .
        extra_requirements:
           - docs
   system_packages: false

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
  jobs:
    post_checkout:
      - git fetch --unshallow
    pre_install:
      - git update-index --assume-unchanged docs/conf.py
      - pip install -U setuptools setuptools_scm[toml]
