
variables:
  qtversion: 5.12.1

jobs:
- job: Ubuntu_1604
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - script: |
      sudo apt-get update
      sudo apt-get -y install python3 python3-requests p7zip-full
      cd $(Build.BinariesDirectory)
      $(Build.SourcesDirectory)/qli-installer.py $(qtversion) linux desktop
      ls -lR $(qtversion)

- job: macOS
  pool:
    vmImage: 'macOS-10.13'
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.6'
      architecture: 'x64'
  - script: |
      brew install p7zip
      python -m pip install requests
      cd $(Build.BinariesDirectory)
      $(Build.SourcesDirectory)/qli-installer.py $(qtversion) mac desktop
      ls -lR $(qtversion)

- job: Windows64
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.6'
      architecture: 'x64'
  - script: |
      cinst -y 7zip
      python -m pip install requests
      cd $(Build.BinariesDirectory)
      python $(Build.SourcesDirectory)/qli-installer.py $(qtversion) windows desktop win64_msvc2017_64
      ls -lR $(qtversion)

