
variables:
  qtversion: 5.12.1

jobs:
- job: Ubuntu_1604_py3
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.6'
      architecture: 'x64'
  - script: |
      python -m pip install flake8 twine
      flake8 .
    displayName: 'Run lint tests'
  - script: |
      sudo apt-get update
      sudo apt-get -y install p7zip-full
  - task: PythonScript@0
    inputs:
      scriptSource: filePath
      scriptPath: $(Build.SourcesDirectory)/aqtinst
      arguments: $(qtversion) linux desktop
      workingDirectory: $(Build.BinariesDirectory)
    displayName: install qt
  - script: |
      python setup.py sdist bdist_wheel
      echo twine upload dist/*

- job: Ubuntu_1604_py2
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '2.7'
      architecture: 'x64'
  - script: |
      sudo apt-get update
      sudo apt-get -y install p7zip-full
  - task: PythonScript@0
    inputs:
      scriptSource: filePath
      scriptPath: $(Build.SourcesDirectory)/aqtinst
      arguments: $(qtversion) linux desktop
      workingDirectory: $(Build.BinariesDirectory)
    displayName: install qt
  - script: ls -lR $(Build.BinariesDirectory)
  
- job: macOS
  pool:
    vmImage: 'macOS-10.13'
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.6'
      architecture: 'x64'
  - script: brew install p7zip
  - task: PythonScript@0
    inputs:
      scriptSource: filePath
      scriptPath: $(Build.SourcesDirectory)/aqtinst
      arguments: $(qtversion) mac desktop
      workingDirectory: $(Build.BinariesDirectory)
    displayName: install qt
  - script: ls -lR $(Build.BinariesDirectory)

- job: Windows
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.6'
      architecture: 'x64'
  - script: cinst -y 7zip
  - task: PythonScript@0
    inputs:
      scriptSource: filePath
      scriptPath: $(Build.SourcesDirectory)/aqtinst
      arguments: $(qtversion) windows desktop win64_msvc2017_64
      workingDirectory: $(Build.BinariesDirectory)
    displayName: install qt
  - script: ls -lR $(Build.BinariesDirectory)

