version: 1
formatters:
  brief:
    format: '%(message)s'
  default:
    format: '%(asctime)s %(levelname)-8s %(name)-15s %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'
handlers:
  console:
    class: logging.StreamHandler
    level: WARN
    formatter: brief
    stream: ext://sys.stdout
  file:
    class : logging.FileHandler
    formatter: default
    filename: aqtinstall.log
root:
  level: INFO
  handlers:
  - console
  - file