name: Check documents and package by twine

on: push

jobs:
  check_document:
    name: Check packaging 📦 document with twine
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 20
    - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install tools
      run: python -m pip install build twine --user
    - name: Build a binary wheel and a source tarball
      run: python -m build --source --binary --out-dir dist/ ./
    - name: check
      run: tox
