name: Test on GH actions environment

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macOS-latest, ubuntu-latest]
        py: [3.6, 3.7, 3.8]
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 20
      - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.py }}
      - name: Install pep517
        run: python -m pip install pep517 --user
      - name: Build a binary wheel
        run: python -m pep517.build --binary --out-dir dist/ ./
      - name: Install wheel
        run: python -m pip install dist/*.whl
      - name: Run Aqt
        env:
          qtver: 5.14.0
        run: |
          import os
          import subprocess
          command_line = ["python", "-m", "aqt", "install"]
          platform = "${{ matrix.os }}"
          if platform == "windows-latest":
            args = [os.environ["qtver"], "windows", "desktop", "win64_mingw73"]
          elif platform == "macOS-latest":
            args = [os.environ["qtver"], "mac", "desktop", "clang_64"]
          else:
            args = [os.environ["qtver"], "linux", "desktop", "gcc_64"]
          command_line.extend(args)
          try:
            subprocess.run(command_line, check=True)
          except subprocess.CalledProcessError as cpe:
            exit(cpe.returncode)
        shell: python
